// Generated by CoffeeScript 1.6.3
var express, handle;

express = require('../hamlet').__express;

handle = function(err, str) {
  console.log(err);
  return console.log(str);
};

express('test/wrapped.hamlet', {}, handle);
